#+title: Structure and Interpretation of Classical Mechanics
#+subtitle: Computational Physics!
#+startup: indent
#+date: 2020-05-26

Welcome to my tour of Structure and Interpretation of Classical Mechanics. I'm
working on this book to develop my sense of the best way to do research in
public; this book is heavy on math, programming and visualization, and should
stress the normal tools.

I'm attempting to take notes in on org-mode file, and generate all my code from
there. Let's see how it goes!

* Lagrangian Mechanics
  :PROPERTIES:
  :header-args: :eval no-export
  :END:

** Configuration Spaces

Discuss the section here.

*** Exercise 1.1, p5 and 1.2, p8

For each of the mechanical systems described below, give the number of degrees
of freedom of the configuration space.

(Exercise 1.2 asks about the generalized coordinates of each, so I'll note those
here too.)

1. Three juggling pins.

   **18 degrees of freedom** for three juggling pins - 3 position, 3 angles for
   each. OR **15** total, if you assume that the pin is symmetric; then you just
   need two degrees of tilt.

2. A spherical pendulum consisting of a point mass (the pendulum bob) hanging
   from a rigid massless rod attached to a fixed support point. The pendulum bob
   may move in any direction subject to the constraint imposed by the rigid rod.
   The point mass is subject to the uniform force of gravity.

   Spherical pendulum,hanging from a fixed support has **two degrees of
   freedom**, one for each angle.

3. Spherical DOUBLE pendulum has **four degrees of freedom**; two angles from
   previous, plus two more angles for the second pendulum off of the first.

   A spherical double pendulum, consisting of one point mass hanging from a
   rigid massless rod attached to a second point mass hanging from a second
   massless rod attached to a fixed support point. The point masses are subject
   to the uniform force of gravity.

4. A point mass sliding without friction on a rigid curved wire.

   **1 degree of freedom**, distance along the wire.

5. A top consisting of a rigid axisymmetric body with one point on the symmetry
   axis of the body attached to a fixed support, subject to a uniform
   gravitational force.

   Axisymmetric top has **TWO degrees of freedom**, for the angles off of
   vertical. But then we can't talk about its speed, so that's a little strange.
   I guess it has an angular momentum as a property, but that's not a
   coordinate.

6. The same as e, but not axisymmetric.

   We now have **THREE degrees of freedom**, one more for the angle of the top's
   rotation.

** 1.2: Generalized Coordinates

*** Exercise 1.3

Fermat Optics. It's in the foldede section in the blue notebook. Do it again!

*** Exercise 1.4
*** Exercise 1.5
*** Exercise 1.6
*** Exercise 1.7
*** Exercise 1.8
*** Exercise 1.9
*** Exercise 1.10
*** Exercise 1.11
*** Exercise 1.12
*** Exercise 1.13
*** Exercise 1.14
*** Exercise 1.15
*** Exercise 1.16
*** Exercise 1.17
*** Exercise 1.18
*** Exercise 1.19
*** Exercise 1.20
*** Exercise 1.21
*** Exercise 1.22
*** Exercise 1.23
*** Exercise 1.24
*** Exercise 1.25
*** Exercise 1.26
*** Exercise 1.27
*** Exercise 1.28
*** Exercise 1.29
*** Exercise 1.30
*** Exercise 1.31
*** Exercise 1.32
*** Exercise 1.33
*** Exercise 1.34
*** Exercise 1.35
*** Exercise 1.36
*** Exercise 1.37
*** Exercise 1.38
*** Exercise 1.39
*** Exercise 1.40
*** Exercise 1.41
*** Exercise 1.42
*** Exercise 1.43
*** Exercise 1.44

** 1.3: The Principle of Stationary Action
** 1.4: Computing Actions
** 1.5: The Euler–Lagrange Equations
*** 1.5.1 Derivation of the Lagrange Equations
*** 1.5.2 Computing Lagrange's Equations
** 1.6: How to Find Lagrangians
*** 1.6.1: Coordinate Transformations
*** 1.6.2: Systems with Rigid Constraints
*** 1.6.3: Constraints as Coordinate Transformations
*** 1.6.4: The Lagrangian Is Not Unique
** 1.7: Evolution of Dynamical State
** 1.8: Conserved Quantities
*** 1.8.1: Conserved Momenta
*** 1.8.2: Energy Conservation
*** 1.8.3: Central Forces in Three Dimensions
*** 1.8.4: The Restricted Three-Body Problem
*** 1.8.5: Noether's Theorem
** 1.9: Abstraction of Path Functions
** 1.10: Constrained Motion
*** 1.10.1: Coordinate Constraints
*** 1.10.2: Derivative Constraints
*** 1.10.3: Nonholonomic Systems
** 1.11: Summary
** 1.12: Projects
* Rigid Bodies
** 2.1: Rotational Kinetic Energy
** 2.2: Kinematics of Rotation
** 2.3: Moments of Inertia
** 2.4: Inertia Tensor
** 2.5: Principal Moments of Inertia
** 2.6: Vector Angular Momentum
** 2.7: Euler Angles
** 2.8: Motion of a Free Rigid Body
*** 2.8.1: Computing the Motion of Free Rigid Bodies
*** 2.8.2: Qualitative Features
** 2.9: Euler's Equations
** 2.10: Axisymmetric Tops
** 2.11: Spin-Orbit Coupling
*** 2.11.1: Development of the Potential Energy
*** 2.11.2: Rotation of the Moon and Hyperion
*** 2.11.3: Spin-Orbit Resonances
** 2.12: Nonsingular Coordinates and Quaternions
*** 2.12.1: Motion in Terms of Quaternions
** 2.13: Summary
** 2.14: Projects
* Hamiltonian Mechanics
** 3.1: Hamilton's Equations
*** 3.1.1: The Legendre Transformation
*** 3.1.2: Hamilton's Equations from the Action Principle
*** 3.1.3: A Wiring Diagram
** 3.2: Poisson Brackets
** 3.3: One Degree of Freedom
** 3.4: Phase Space Reduction
*** 3.4.1: Lagrangian Reduction
** 3.5: Phase Space Evolution
*** 3.5.1: Phase-Space Description Is Not Unique
** 3.6: Surfaces of Section
*** 3.6.1: Periodically Driven Systems
*** 3.6.2: Computing Stroboscopic Surfaces of Section
*** 3.6.3: Autonomous Systems
*** 3.6.4: Computing Hénon–Heiles Surfaces of Section
*** 3.6.5: Non-Axisymmetric Top
** 3.7: Exponential Divergence
** 3.8: Liouville's Theorem
** 3.9: Standard Map
** 3.10: Summary
** 3.11: Projects
* Phase Space Structure
** 4.1: Emergence of the Divided Phase Space
** 4.2: Linear Stability
*** 4.2.1: Equilibria of Differential Equations
*** 4.2.2: Fixed Points of Maps
*** 4.2.3: Relations Among Exponents
** 4.3: Homoclinic Tangle
*** 4.3.1: Computation of Stable and Unstable Manifolds
** 4.4: Integrable Systems
** 4.5: Poincaré–Birkhoff Theorem
*** 4.5.1: Computing the Poincaré–Birkhoff Construction
** 4.6: Invariant Curves
*** 4.6.1: Finding Invariant Curves
*** 4.6.2: Dissolution of Invariant Curves
** 4.7: Summary
** 4.8: Projects
* Canonical Transformations

**** Exercise 5.1
**** Exercise 5.2
**** Exercise 5.3
**** Exercise 5.4
**** Exercise 5.5
**** Exercise 5.6
**** Exercise 5.7
**** Exercise 5.8
**** Exercise 5.9
**** Exercise 5.10
**** Exercise 5.11
**** Exercise 5.12
**** Exercise 5.13
**** Exercise 5.14
**** Exercise 5.15
**** Exercise 5.16
**** Exercise 5.17
**** Exercise 5.18
**** Exercise 5.19
**** Exercise 5.20

** 5.1: Point Transformations
** 5.2: General Canonical Transformations
*** 5.2.1: Time-Dependent Transformations
*** 5.2.2: Abstracting the Canonical Condition
** 5.3: Invariants of Canonical Transformations
** 5.4: Generating Functions
*** 5.4.1: F1 Generates Canonical Transformations
*** 5.4.2: Generating Functions and Integral Invariants
*** 5.4.3: Types of Generating Functions
*** 5.4.4: Point Transformations
*** 5.4.5: Total Time Derivatives
** 5.5: Extended Phase Space
*** 5.5.1: Poincaré–Cartan Integral Invariant
** 5.6: Reduced Phase Space
** 5.7: Summary
** 5.8: Projects
* Canonical Evolution

** Hamilton–Jacobi Equation

**** Exercise 6.1
**** Exercise 6.2
**** Exercise 6.3
**** Exercise 6.4
**** Exercise 6.5
**** Exercise 6.6
**** Exercise 6.7
**** Exercise 6.8
**** Exercise 6.9
**** Exercise 6.10
**** Exercise 6.11
**** Exercise 6.12

*** Harmonic Oscillator
*** Hamilton–Jacobi Solution of the Kepler Problem
*** F2 and the Lagrangian
*** The Action Generates Time Evolution
** Time Evolution is Canonical
*** Another View of Time Evolution
*** Yet Another View of Time Evolution
** Lie Transforms
** Lie Series
** Exponential Identities
** Summary
** Projects
* Canonical Perturbation Theory

** Perturbation Theory with Lie Series

*** Exercise 7.1
*** Exercise 7.2
*** Exercise 7.3
*** Exercise 7.4
*** Exercise 7.5

** Pendulum as a Perturbed Rotor
*** 7.2.1: Higher Order
*** 7.2.2: Eliminating Secular Terms
** Many Degrees of Freedom
*** 7.3.1: Driven Pendulum as a Perturbed Rotor
** Nonlinear Resonance
*** Pendulum Approximation
*** Reading the Hamiltonian
*** Resonance-Overlap Criterion
*** Higher-Order Perturbation Theory
*** Stability of the Inverted Vertical Equilibrium
** Summary
** Projects
* Scheme
* Our Notation
  :PROPERTIES:
  :header-args: :eval never-export
  :END:

** Exercises

Notation Appendix. This is all about getting cozy with scheme, and with the
various idiosyncracies of the tuple and functional notation.

*** Exercise 9.1 Chain Rule
     :PROPERTIES:
     :header-args+: :tangle ch9/ex9-1.scm :comments org
     :END:

You're supposed to do these by hand, so I'll do that in the textbook. But here,
let's redo them on the machine.

#+begin_src scheme :exports none
(load "ch1/utils.scm")
#+end_src

#+RESULTS:
: ;Loading "ch1/utils.scm"... done
: #| check-f |#

***** Compute $\partial_0 F(x, y)$ and $\partial_1 F(x, y)$

First, let's define the functions we need.

#+begin_src scheme
(define (F x y)
  (* (square x)
     (cube y)))

(define (G x y)
  (up (F x y) y))

(define (H x y)
  (F (F x y) y))
#+end_src

#+RESULTS:
: #| F |#
:
: #| G |#
:
: #| H |#

 You can do this with explicit partials:

#+begin_src scheme :results value raw :exports both :cache yes
(let ((f (down ((partial 0) F) ((partial 1) F))))
  (->tex-equation
   (f 'x 'y)))
#+end_src

#+RESULTS[be9a90487e3a5e53f5a9c479dd79dbd76bd0e18c]:
\begin{equation}
\left[ \matrix{ \displaystyle{ 2 x {y}^{3}} \cr \cr \displaystyle{ 3 {x}^{2} {y}^{2}}} \right]
\end{equation}

Or with the $D$ symbol:

#+begin_src scheme :results value raw :exports both :cache yes
(->tex-equation
 ((D F) 'x 'y))
#+end_src

#+RESULTS[ad5e3457e7a32bea193ba2301f548b99b871656c]:
\begin{equation}
\left[ \matrix{ \displaystyle{ 2 x {y}^{3}} \cr \cr \displaystyle{ 3 {x}^{2} {y}^{2}}} \right]
\end{equation}

Or, we could show that they're equivalent this way:

#+begin_src scheme :results value raw :exports both :cache yes
(let ((f (down ((partial 0) F) ((partial 1) F))))
  (->tex-equation
   (- ((D F) 'x 'y)
      (f 'x 'y))))
#+end_src

#+RESULTS[0409e2cdf711957d7bcfc514a7d127cc790f8835]:
\begin{equation}
\left[ \matrix{ \displaystyle{ 0} \cr \cr \displaystyle{ 0}} \right]
\end{equation}

***** Compute $\partial_0 F(F(x, y), y)$ and $\partial_1 F(F(x, y), y)$

$H$ is already that composition, so:

#+begin_src scheme :results value raw :exports both :cache yes
(->tex-equation
 ((D H) 'x 'y))
#+end_src

#+RESULTS[50be975d97eed6c38ed1ec502c4f297eace9f3df]:
\begin{equation}
\left[ \matrix{ \displaystyle{ 4 {x}^{3} {y}^{9}} \cr \cr \displaystyle{ 9 {x}^{4} {y}^{8}}} \right]
\end{equation}

***** Compute $\partial_0 G(x, y)$ and $\partial_1 G(x, y)$

#+begin_src scheme :results value raw :exports both :cache yes
(->tex-equation
 ((D G) 'x 'y))
#+end_src

#+RESULTS[5038860f9e86fa99d00b56d9e39ac93ee1c9667b]:
\begin{equation}
\left[ \matrix{ \displaystyle{ \left( \matrix{ \displaystyle{ 2 x {y}^{3}} \cr \cr \displaystyle{ 0}} \right)} \cr \cr \displaystyle{ \left( \matrix{ \displaystyle{ 3 {x}^{2} {y}^{2}} \cr \cr \displaystyle{ 1}} \right)}} \right]
\end{equation}

***** Compute $DF(a, b)$, $DG(3, 5)$ and $DH(3a^2, 5b^3)$

#+begin_src scheme :results value raw :exports both :cache yes
(->tex-equation
 (up ((D F) 'a 'b)
     ((D G) 3 5)
     ((D H) (* 3 (square 'a)) (* 5 (cube 'b)))))
#+end_src

#+RESULTS[58f6814dcdb27cedc271a73e19fc1d9c414a2bef]:
\begin{equation}
\left( \matrix{ \displaystyle{ \left[ \matrix{ \displaystyle{ 2 a {b}^{3}} \cr \cr \displaystyle{ 3 {a}^{2} {b}^{2}}} \right]} \cr \cr \displaystyle{ \left[ \matrix{ \displaystyle{ \left( \matrix{ \displaystyle{ 750} \cr \cr \displaystyle{ 0}} \right)} \cr \cr \displaystyle{ \left( \matrix{ \displaystyle{ 675} \cr \cr \displaystyle{ 1}} \right)}} \right]} \cr \cr \displaystyle{ \left[ \matrix{ \displaystyle{ 210937500 {a}^{6} {b}^{27}} \cr \cr \displaystyle{ 284765625 {a}^{8} {b}^{24}}} \right]}} \right)
\end{equation}

*** Exercise 9.2: Computing Derivatives
     :PROPERTIES:
     :header-args+: :tangle ch9/ex9-2.scm :comments org
     :END:

#+begin_src scheme :exports none
(load "ch1/utils.scm")
#+end_src

A further exercise is to try defining the functions so that they use explicit
tuples, so you can compose them:

#+begin_src scheme
(define (F* v)
  (let ((x (ref v 0))
        (y (ref v 1)))
    (* (square x) (cube y))))

(define (G* v)
  (let ((x (ref v 0))
        (y (ref v 1)))
    (up (F* v) y)))

(define H* (compose F* G*))
#+end_src

#+RESULTS:
: #| F* |#
:
: #| G* |#
:
: #| H* |#

to be really pro, I'd make a function that takes these as arguments and prints a
nice formatted exercise output. Let's do the final exercise, for fun:

#+begin_src scheme :results value raw :exports both :cache yes
(->tex-equation
 (up ((D F*) (up 'a 'b))
     ((D G*) (up 3 5))
     ((D H*) (up (* 3 (square 'a)) (* 5 (cube 'b))))))
#+end_src

#+RESULTS[cd4f5c223d1859bb16d66bba402758a0d247e740]:
\begin{equation}
\left( \matrix{ \displaystyle{ \left[ \matrix{ \displaystyle{ 2 a {b}^{3}} \cr \cr \displaystyle{ 3 {a}^{2} {b}^{2}}} \right]} \cr \cr \displaystyle{ \left[ \matrix{ \displaystyle{ \left( \matrix{ \displaystyle{ 750} \cr \cr \displaystyle{ 0}} \right)} \cr \cr \displaystyle{ \left( \matrix{ \displaystyle{ 675} \cr \cr \displaystyle{ 1}} \right)}} \right]} \cr \cr \displaystyle{ \left[ \matrix{ \displaystyle{ 210937500 {a}^{6} {b}^{27}} \cr \cr \displaystyle{ 284765625 {a}^{8} {b}^{24}}} \right]}} \right)
\end{equation}

* Org-Mode Demo
  :PROPERTIES:
  :header-args: :eval no-export
  :END:

This is an example of how we might structure an org-mode file that can export
out to Github flavored Markdown, or to a PDF.

First, let's get some code loaded up and written. Here's a block that converts
polar coordinates to rectangular coordinates.

#+name: p->r
#+begin_src scheme :eval no
(define (p->r local)
  (let* ((polar-tuple (coordinate local))
         (r (ref polar-tuple 0))
         (phi (ref polar-tuple 1))
         (x (* r (cos phi)))
         (y (* r (sin phi))))
    (up x y)))
#+end_src

This is some good stuff.

#+begin_src scheme :results output :noweb yes :comments both
(load "ch1/utils.scm")

<<p->r>>

<<spherical->rect>>
#+end_src

And another, that gets us from spherical to rectangular.

#+name: spherical->rect
#+begin_src scheme :eval no
(define (spherical->rect local)
  (let* ((spherical-tuple (coordinate local))
         (r (ref spherical-tuple 0))
         (theta (ref spherical-tuple 1))
         (phi (ref spherical-tuple 2)))
    (up (* r (sin theta) (cos phi))
        (* r (sin theta) (sin phi))
        (* r (cos theta)))))
#+end_src

#+RESULTS[f4f039075baf66ba4fe071844815bfcffe281eaa]:
: ;Loading "ch1/utils.scm"... done
: #| "" |#

This block will generate a LaTeX version of the code I've supplied:

#+begin_src scheme :results value raw :exports both :cache yes
(->tex-equation
 ((+ (literal-function 'c)
     (D (literal-function 'z)))
  't)
 "eq:masterpiece")
#+end_src

#+RESULTS[b383d2f5d6c252ac04a5f44aaeaec678132b8449]:
\begin{equation}
c\left( t \right) + Dz\left( t \right)
\label{eq:masterpiece}
\end{equation}

You can even reference these with equation numbers, like Equation \eqref{eq:masterpiece} above.

#+begin_src scheme :results value :exports both :cache yes
(up 1 2 't)
#+end_src

#+RESULTS:
: #|
: (up 1 2 t)
: |#

*** Equations

Here's (a test) of $a = bc$ and more $$ \alpha_t $$ equations:

And again this is a thing:

\[
e^{i\pi} = -1
\]

\[
\int_0^\infty e^{-x^2} dx = \frac{\sqrt{\pi}}{2}
\]
